# Generated by Django 3.0.2 on 2021-04-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210410_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='neighborhood_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Neighborhood'),
        ),
    ]
