# Generated by Django 3.0.2 on 2021-04-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210410_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emergency_service',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='heath_center',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='police_station',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
