# Generated by Django 3.0.2 on 2021-04-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210411_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='business',
            name='neighborhood_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Neighborhood'),
        ),
    ]
