# Generated by Django 3.0.2 on 2021-04-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210411_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
