# Generated by Django 3.0.2 on 2021-04-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210411_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency_service',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='heath_center',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='police_station',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
