# Generated by Django 3.0.2 on 2021-04-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210411_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency_service',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='heath_center',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='police_station',
            name='neighborhood',
        ),
    ]
