# Generated by Django 3.0.2 on 2021-04-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210411_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Neighborhood'),
        ),
    ]
