# Generated by Django 3.0.2 on 2021-04-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210411_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heath_center',
            name='neighborhood',
            field=models.CharField(max_length=50),
        ),
    ]
