# Generated by Django 3.0.2 on 2021-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210412_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency_service',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='police_station',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
