# Generated by Django 3.0.2 on 2021-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20210412_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='neighborhood_name',
        ),
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
