# Generated by Django 3.0.2 on 2021-04-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210412_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='title',
            new_name='name',
        ),
    ]
