# Generated by Django 3.0.2 on 2021-04-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210412_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
