# Generated by Django 3.0.2 on 2021-04-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20210412_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='neighborhood_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Neighborhood'),
        ),
    ]
