# Generated by Django 3.0.2 on 2021-04-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_business_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verification_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
